version: '3'

services:
  db:
    container_name: monorepo-mongo
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  mongo-express:
    container_name: monorepo-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    env_file:
      - .env
  app-py:
    container_name: app-py
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env
    # environment:
    #   - MONGO_SERVER=db